


import json
import sys
import os
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.llama_models import _find_ollama_root, list_available_models, resolve_model_path

_MODELS_JSON = Path(__file__).resolve().parent.parent / "models.json"


def main():
    print("=" * 60)
    print("  Hivemind llama.cpp model scanner")
    print("=" * 60)
    print()

    ollama_root = _find_ollama_root()
    if ollama_root:
        print(f"Ollama models found: {ollama_root}")
    else:
        print("No Ollama directory found.")
        print("  Add GGUFs manually to models.json.")
        return

    print()
    print("Scanning models...")
    print()

    models = list_available_models()
    mapping = {}
    missing = []

    for model in sorted(models):
        if model.startswith("gguf/"):
            continue
        path = resolve_model_path(model)
        if path:
            mapping[model] = str(path)
            size_gb = path.stat().st_size / (1024**3)
            print(f"  {model:<30} -> {path.name} ({size_gb:.1f} GB)")
        else:
            missing.append(model)
            print(f"  {model:<30} -> GGUF not found")

    print()
    print(f"Found: {len(mapping)} / {len(models)} models")

    if missing:
        print()
        print("Missing models (GGUF not locatable):")
        for m in missing:
            print(f"  - {m}")
        print()
        print("Add these manually to models.json:")
        print('  "model:tag": "C:/path/to/file.gguf"')

    output = {}
    output["_generated"] = "auto-generated by scan_models.py"
    output["_note"] = "Manual overrides take precedence. Paths can be adjusted."
    output.update(mapping)

    _MODELS_JSON.write_text(
        json.dumps(output, indent=2, ensure_ascii=False),
        encoding="utf-8"
    )

    print()
    print(f"models.json written: {_MODELS_JSON}")
    print()
    print("Next steps:")
    print("  1. Check models.json (optional: replace worse quantizations with better ones)")
    print("  2. Check llama_config.py (LLAMA_BIN, GPU_LAYERS, KV_CACHE_TYPE)")
    print("  3. Run start_llama.bat")


if __name__ == "__main__":
    main()
